baseURL = "/"
title = "LinuxAdmin.blog"
theme = "bookworm-light-hugo"
timeZone = "Europe/Istanbul"
pagination.pagerSize = 5
summaryLength = 10
[module]
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'
[outputs]
home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]
[imaging]
resampleFilter = "lanczos"
quality = 90
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'solarized-dark'
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true